services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: genai-demo-es
    environment:
      "discovery.type": "single-node"
      "xpack.security.enabled": "false"
      "xpack.security.http.ssl.enabled": "false"
    ports:
      - "9200:9200"
